---
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      name: "kubeme-toolkit"
    name: "kubeme-toolkit"
    namespace: "kube-system"
  spec:
    replicas: 1
    selector:
      name: "kubeme-toolkit"
    template:
      metadata:
        labels:
          name: "kubeme-toolkit"
      spec:
        containers:
          -
            image: "onemorehill/kubeme-toolkit:v0.1.0"
            name: "kubeme-toolkit"
            command:
              - "/kubeme-toolkit"
            resources:
              limits:
                cpu: 50m
                memory: 100Mi

---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      name: "kubeme-toolkit"
    name: "kubeme-toolkit"
    namespace: "kube-system"
  spec:
    type: "LoadBalancer"
    ports:
      -
        port: 80
        targetPort: 8001
    selector:
      name: "kubeme-toolkit"
